<?php

namespace AppBundle\Repository;

/**
 * DomainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomainRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllInArray()
    {
        $query = $this
            ->getEntityManager()
            ->createQuery("SELECT d FROM AppBundle:Domain d");

        return $query->getArrayResult();
    }
}
